apiVersion: v2
name: opentelemetry-collector
version: 0.0.1
description: This Chart deploys opentelemetry-collector with preconfigured values.
dependencies:
  - name: opentelemetry-collector
    version: 0.122.0
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
