opentelemetry-collector:
    mode: "daemonset"

    image:
        repository: "otel/opentelemetry-collector"

    command:
        name: "otelcol"

    presets:
        hostMetrics:
            enabled: true
        kubernetesAttributes:
            enabled: true
            extractAllPodLabels: true
            extractAllPodAnnotations: true
        kubeletMetrics:
            enabled: true