apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: cluster-collector
spec:
  mode: statefulset
  targetAllocator:
    enabled: true
    image: {{.Values.targetAllocator.image.registry}}:{{.Values.targetAllocator.image.tag}}
    serviceAccount: {{.Values.targetAllocator.serviceAccountName}}
    prometheusCR:
      enabled: true
      podMonitorSelector: {}
      serviceMonitorSelector: {}
  #render additional volume mounts and volumes
  {{- if .Values.additionalVolumes}} 
  volumeMounts: 
  {{- end}}
  {{- range .Values.additionalVolumes }}
   - name: {{.name}}
     mountPath: {{.mountPath}}
     readOnly: {{.readOnly}}
  {{- end }}
  {{- if .Values.additionalVolumes}} 
  volumes:
  {{- end }}
  {{- range .Values.additionalVolumes }}
   - name: {{.name}}
     hostPath:
       path: {{.hostPath}}
  {{- end }}
  config: {{ .Values.config | toYaml | nindent 4 }}