apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: cluster-collector
spec:
  mode: statefulset
  targetAllocator:
    enabled: true
    image: {{.Values.targetAllocator.image.registry}}:{{.Values.targetAllocator.image.tag}}
    serviceAccount: {{.Values.targetAllocator.serviceAccountName}}
    prometheusCR:
      enabled: true
      podMonitorSelector: {}
      serviceMonitorSelector: {}
  config: {{ .Values.config | toYaml | nindent 4 }}